# Generated by Django 5.1 on 2024-08-14 09:53

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_countries.fields.CountryField(max_length=2)),
                ('full_name', models.CharField(max_length=300)),
                ('name_of_group', models.CharField(blank=True, max_length=200, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=10, null=True)),
                ('visa', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('liaison_person', models.CharField(blank=True, max_length=300, null=True)),
                ('flight_path', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_arrival', models.DateTimeField(blank=True, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('hotel_in_tashkent', models.CharField(blank=True, max_length=300, null=True)),
                ('transports_in_tashkent', models.CharField(blank=True, max_length=300, null=True)),
                ('tashken_samarkand', models.CharField(blank=True, max_length=300, null=True)),
                ('transports_in_samarkand', models.CharField(blank=True, max_length=300, null=True)),
                ('hotel_in_samarkand', models.CharField(blank=True, max_length=300, null=True)),
                ('departure_from', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_departure', models.DateTimeField(blank=True, null=True)),
                ('departure_flight_number', models.CharField(blank=True, max_length=200, null=True)),
                ('departed', models.BooleanField(blank=True, default=False, null=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('language', models.ManyToManyField(blank=True, to='app.language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('guests', models.ManyToManyField(blank=True, to='app.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.moderator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.user')),
            ],
        ),
    ]
