# Generated by Django 5.1 on 2024-08-15 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='moderator',
        ),
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ManyToManyField(related_name='messages', to='app.user'),
        ),
    ]
