# Generated by Django 5.1 on 2024-08-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_message_moderator_message_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
