# Generated by Django 5.0 on 2024-08-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_timestamp_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.ManyToManyField(to='app.category'),
        ),
    ]
