# Generated by Django 5.0 on 2024-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_message_category_message_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='users', to='app.guest'),
        ),
    ]
