# Generated by Django 5.0 on 2024-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='messages', to='app.user'),
        ),
    ]
