# Generated by Django 5.0 on 2024-08-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_message_category_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='date_of_arrival',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='departed',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='flight_path',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='tashken_samarkand',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='transports_in_tashkent',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='visa',
        ),
    ]
