# Generated by Django 5.0 on 2024-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_message_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
    ]
