"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from .config_reader import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kjf)3v7xxb)hc@0%4c#lun-%o$%++&9p=+ngw(v57^$s6gyi3)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.debug

ALLOWED_HOSTS = config.allowed_hosts
CSRF_TRUSTED_ORIGINS = config.allowed_hosts

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'multiselectfield',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config.django_db_engine.get_secret_value(),
        'NAME': config.django_db_name.get_secret_value(),
        'USER': config.django_db_user.get_secret_value(),
        'PASSWORD': config.django_db_password.get_secret_value(),
        'HOST': config.django_db_host.get_secret_value(),
        'PORT': config.django_db_port.get_secret_value(),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'uz-UZ'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'app.User'
COUNTRIES_OVERRIDE = {
    "AF": "Afg'oniston",
    "AL": "Albaniya",
    "DZ": "Jazoir",
    "AD": "Andorra",
    "AO": "Angola",
    "AG": "Antigua va Barbuda",
    "AR": "Argentina",
    "AM": "Armaniston",
    "AU": "Avstraliya",
    "AT": "Avstriya",
    "AZ": "Ozarbayjon",
    "BS": "Bagama orollari",
    "BH": "Bahrayn",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgiya",
    "BZ": "Beliz",
    "BJ": "Benin",
    "BT": "Butan",
    "BO": "Boliviya",
    "BA": "Bosniya va Gertsegovina",
    "BW": "Botsvana",
    "BR": "Braziliya",
    "BN": "Bruney",
    "BG": "Bolgariya",
    "BF": "Burkina-Faso",
    "BI": "Burundi",
    "CV": "Kabo-Verde",
    "KH": "Kambodja",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CF": "Markaziy Afrika Respublikasi",
    "TD": "Chad",
    "CL": "Chili",
    "CN": "Xitoy",
    "CO": "Kolumbiya",
    "KM": "Komor orollari",
    "CG": "Kongo",
    "CR": "Kosta-Rika",
    "HR": "Xorvatiya",
    "CU": "Kuba",
    "CY": "Kipr",
    "CZ": "Chexiya",
    "DK": "Daniya",
    "DJ": "Jibuti",
    "DM": "Dominika",
    "DO": "Dominikan Respublikasi",
    "EC": "Ekvador",
    "EG": "Misr",
    "SV": "Salvador",
    "GQ": "Ekvatorial Gvineya",
    "ER": "Eritreya",
    "EE": "Estoniya",
    "SZ": "Esvatini",
    "ET": "Efiopiya",
    "FJ": "Fiji",
    "FI": "Finlandiya",
    "FR": "Fransiya",
    "GA": "Gabon",
    "GM": "Gambiya",
    "GE": "Gruziya",
    "DE": "Germaniya",
    "GH": "Gana",
    "GR": "Gretsiya",
    "GD": "Grenada",
    "GT": "Gvatemala",
    "GN": "Gvineya",
    "GW": "Gvineya-Bisau",
    "GY": "Gayana",
    "HT": "Gaiti",
    "HN": "Gonduras",
    "HU": "Vengriya",
    "IS": "Islandiya",
    "IN": "Hindiston",
    "ID": "Indoneziya",
    "IR": "Eron",
    "IQ": "Iroq",
    "IE": "Irlandiya",
    "IL": "Isroil",
    "IT": "Italiya",
    "JM": "Yamayka",
    "JP": "Yaponiya",
    "JO": "Iordaniya",
    "KZ": "Qozog'iston",
    "KE": "Keniya",
    "KI": "Kiribati",
    "KW": "Kuvayt",
    "KG": "Qirg'iziston",
    "LA": "Laos",
    "LV": "Latviya",
    "LB": "Livan",
    "LS": "Lesoto",
    "LR": "Liberiya",
    "LY": "Liviya",
    "LI": "Lixtenshteyn",
    "LT": "Litva",
    "LU": "Lyuksemburg",
    "MG": "Madagaskar",
    "MW": "Malavi",
    "MY": "Malayziya",
    "MV": "Maldiv orollari",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall orollari",
    "MR": "Mavritaniya",
    "MU": "Mavrikiy",
    "MX": "Meksika",
    "FM": "Mikroneziya",
    "MD": "Moldova",
    "MC": "Monako",
    "MN": "Mongoliya",
    "ME": "Chernogoriya",
    "MA": "Marokash",
    "MZ": "Mozambik",
    "MM": "Myanma",
    "NA": "Namibiya",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Gollandiya",
    "NZ": "Yangi Zelandiya",
    "NI": "Nikaragua",
    "NE": "Niger",
    "NG": "Nigeriya",
    "KP": "Shimoliy Koreya",
    "MK": "Shimoliy Makedoniya",
    "NO": "Norvegiya",
    "OM": "Ummon",
    "PK": "Pokiston",
    "PW": "Palau",
    "PS": "Falastin",
    "PA": "Panama",
    "PG": "Papua-Yangi Gvineya",
    "PY": "Paragvay",
    "PE": "Peru",
    "PH": "Filippin",
    "PL": "Polsha",
    "PT": "Portugaliya",
    "QA": "Qatar",
    "RO": "Ruminiya",
    "RU": "Rossiya",
    "RW": "Ruanda",
    "KN": "Sent-Kits va Nevis",
    "LC": "Sent-Lyusiya",
    "VC": "Sent-Vinsent va Grenadinlar",
    "WS": "Samoa",
    "SM": "San-Marino",
    "ST": "San-Tome va Prinsipe",
    "SA": "Saudiya Arabistoni",
    "SN": "Senegal",
    "RS": "Serbiya",
    "SC": "Seyshel orollari",
    "SL": "Syerra-Leone",
    "SG": "Singapur",
    "SK": "Slovakiya",
    "SI": "Sloveniya",
    "SB": "Solomon orollari",
    "SO": "Somali",
    "ZA": "Janubiy Afrika",
    "KR": "Janubiy Koreya",
    "SS": "Janubiy Sudan",
    "ES": "Ispaniya",
    "LK": "Shri-Lanka",
    "SD": "Sudan",
    "SR": "Surinam",
    "SE": "Shvetsiya",
    "CH": "Shveytsariya",
    "SY": "Suriya",
    "TW": "Tayvan",
    "TJ": "Tojikiston",
    "TZ": "Tanzaniya",
    "TH": "Tailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad va Tobago",
    "TN": "Tunis",
    "TR": "Turkiya",
    "TM": "Turkmaniston",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraina",
    "AE": "Birlashgan Arab Amirliklari",
    "GB": "Birlashgan Qirollik",
    "US": "Qo'shma Shtatlar",
    "UY": "Urugvay",
    "UZ": "O'zbekiston",
    "VU": "Vanuatu",
    "VA": "Vatikan",
    "VE": "Venesuela",
    "VN": "Vyetnam",
    "YE": "Yaman",
    "ZM": "Zambiya",
    "ZW": "Zimbabve",
}
